name: Package Sit-Stand-Reminder with Pyinstaller

on:
  push:
    tags:
     - '*'
    branches:
      - develop
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: sit-stand-reminder
        path: ./dist/windows/sit_stand_reminder.exe
    
    - name: Update README
      id: update-readme
      run: |
        echo "Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }} and Run ID is ${{ github.run_id }}"
        sed -i "s#\[sit-stand-reminder.exe.*#[sit-stand-reminder.exe](https://github.com/manojmanivannan/sit-stand-reminder/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }})#" README.md

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update README
        branch: master