name: Package Sit-Stand-Reminder with PyInstaller

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - name: Upload Artifact
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: sit-stand-reminder
          path: ./dist/windows/sit_stand_reminder.exe

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          release_name: "Sit-Stand-Reminder Latest Release"
          body: "This is the latest build of Sit-Stand-Reminder."
          files: ./dist/windows/sit_stand_reminder.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: |
          sed -i "s#\[sit-stand-reminder.exe.*#[sit-stand-reminder.exe](https://github.com/${{ github.repository }}/releases/latest/download/sit_stand_reminder.exe)#" README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README with latest release link"
