name: Package Sit-Stand-Reminder with Pyinstaller

on:
  push:
    tags:
     - '*'
    branches:
      - develop
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v3
      with:
        name: sit-stand-reminder
        path: ./dist/windows/sit_stand_reminder.exe
